
export const ADDRESS_HOST = 'http://20.12.0.2'

export const PORT_DICTIONARY = '8990'
export const HOST_GRPC_DICTIONARY = ADDRESS_HOST + ':' + PORT_DICTIONARY

export const PORT_DATA = '8991'
export const HOST_GRPC_DATA = ADDRESS_HOST + ':' + PORT_DATA

export const PORT_AUTHENTICATION = '8989'
export const HOST_GRPC_AUTHENTICATION = ADDRESS_HOST + ':' + PORT_AUTHENTICATION
